name: Build, Push and Deploy Docker Image with MongoDB connection

on:
  push:
    branches:
      - main

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Azure Web App for Containers
        uses: azure/webapps-deploy@v3
        with:
          app-name: WA-Deployment
          slot-name: Production
          images: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}

      - name: Configure MongoDB environment variables in Azure Web App
        uses: azure/cli@v1
        with:
          inlineScript: |
            az webapp config appsettings set \
              --name WA-Deployment \
              --resource-group deploy \
              --settings MONGO_URI="${{ secrets.MONGO_URI }}" \
                         MONGO_USERNAME="${{ secrets.MONGO_USERNAME }}" \
